language: r
cache: packages

r: bioc-release

latex: false

pandoc_version: 2.0.1.1

# before_install:
  # For installing sf
  # sf need GDAL over 2.2, so add this repo
  # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  # - sudo apt-get --yes --force-yes update -qq
  # - sudo apt-get install --yes libudunits2-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'